export const LOGIN = 'LOGIN';
export const GET_COUNTRY_REGION_LIST = 'GETCOUNTRYREGIONLIST';
export const GET_FUNDING_LIST = 'GET_FUNDING_LIST';
export const GET_ROLE_LIST = 'GET_ROLE_LIST';
export const SAVE_FORM_POSITION = 'SAVE_FORM_POSITION';
